name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', 'ruby-head', 'jruby-head']
        task: [test, spec]
        include:
        # run rubocop against lowest supported ruby
        - os: ubuntu-latest
          ruby: '2.7'
          task: rubocop
    # do not crash the build when latest fails (since it is a moving target)
    continue-on-error: ${{ contains(matrix.ruby, '-head') }}
    name: ${{ matrix.ruby }} rake ${{ matrix.task }}
    steps:
    - uses: actions/checkout@v3
    # actions/setup-ruby did not support truffle or bundler caching
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake ${{ matrix.task }}
